services:
  db:
    env_file:
      - .env
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - PGDATA:/var/lib/postgresql/data/pgdata
